ffnn::traits::Unique Class Reference
An object with a unique ID.
#include `unique.h`
Public Member Functions
Unique ()
Default constructor.
const std::string & getID () const
Returns an ID.
void setID (const std::string &id)
Sets an ID.
Protected Member Functions
FFNN_REGISTER_SERIALIZABLE ()
void save (OutputArchive &ar, VersionType) const
void load (InputArchive &ar, VersionType)
Additional Inherited Members
Detailed Description
An object with a unique ID.
Constructor & Destructor Documentation
ffnn::traits::Unique::Unique () [inline]
Default constructor.
Member Function Documentation
ffnn::traits::Unique::FFNN_REGISTER_SERIALIZABLE () [protected]
const std::string& ffnn::traits::Unique::getID () const [inline]
Returns an ID.
Returns
ID
Referenced by ffnn::layer::Layer< ValueType >::save(), and ffnn::layer::internal::Interface< ValueType >::~Interface().
void ffnn::traits::Unique::load (InputArchive & ar, VersionType) [inline], [protected], [virtual]
Implements ffnn::traits::Serializable.
Reimplemented in ffnn::layer::ConvolutionVolume< ValueType, HeightAtCompileTime, WidthAtCompileTime, DepthAtCompileTime, FilterCountAtCompileTime, Mode >, ffnn::layer::Convolution< ValueType, HeightAtCompileTime, WidthAtCompileTime, DepthAtCompileTime, FilterHeightAtCompileTime, FilterWidthAtCompileTime, FilterCountAtCompileTime, StrideAtCompileTime, Mode, _HiddenLayerShape >, ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::Layer< ValueType >, ffnn::layer::internal::Interface< ValueType >, ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, ffnn::layer::Hidden< ValueType, _HiddenLayerShape >, and ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >.
Referenced by ffnn::layer::internal::Interface< ValueType >::load().
void ffnn::traits::Unique::save (OutputArchive & ar, VersionType) const [inline], [protected], [virtual]
Implements ffnn::traits::Serializable.
Reimplemented in ffnn::layer::ConvolutionVolume< ValueType, HeightAtCompileTime, WidthAtCompileTime, DepthAtCompileTime, FilterCountAtCompileTime, Mode >, ffnn::layer::Convolution< ValueType, HeightAtCompileTime, WidthAtCompileTime, DepthAtCompileTime, FilterHeightAtCompileTime, FilterWidthAtCompileTime, FilterCountAtCompileTime, StrideAtCompileTime, Mode, _HiddenLayerShape >, ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::Layer< ValueType >, ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, ffnn::layer::Hidden< ValueType, _HiddenLayerShape >, ffnn::layer::internal::Interface< ValueType >, and ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >.
Referenced by ffnn::layer::internal::Interface< ValueType >::save().
void ffnn::traits::Unique::setID (const std::string & id) [inline]
Sets an ID.
Parameters
id ID to set
Referenced by Unique().
The documentation for this class was generated from the following file:
/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/internal/traits/unique.h