ffnn::layer::Layer< ValueType > Class Template Reference
Base object for all layer types.
#include `layer.h`
Public Types
using Base = internal::Unique
Base type alias.
using Self = Layer< ValueType >
Self type alias.
typedef boost::shared_ptr< Self > Ptr
Shared resource standardization.
typedef boost::shared_ptr
*
< const Self > ConstPtr
Constant shared resource standardization.
typedef ValueType ScalarType
Scalar type standardization.
typedef ffnn::size_type SizeType
Size type standardization.
typedef ffnn::offset_type OffsetType
Offset type standardization.
typedef Shape< SizeType > ShapeType
Dimension type standardization.
typedef std::conditional
*
< std::is_floating_point
*
< ValueType >::value,
*
std::vector< ValueType,
*
Eigen::aligned_allocator
*
< ValueType > >, std::vector
*
< ValueType >, >::type BufferType
Buffer type standardization.
Public Member Functions
Layer (const ShapeType &input_shape, const ShapeType &output_shape)
Setup constructor.
virtual ~Layer ()
virtual bool initialize ()
Initialize the layer.
virtual bool update ()=0
Applies layer weight updates.
virtual bool forward ()=0
Forward value propagation.
virtual bool backward ()=0
Backward value propagation.
virtual OffsetType connectToForwardLayer (const Self &next, OffsetType offset)=0
Maps outputs of this layer to inputs of the next.
const BufferType & getInputBuffer () const
Exposes const reference to raw data input buffer.
const BufferType & getBackwardErrorBuffer () const
Exposes const reference to raw data backward-error buffer.
const ShapeType & getInputShape () const
Returns the Interface input dimension oject.
const ShapeType & getOutputShape () const
Returns the Interface output dimension oject.
virtual SizeType evaluateInputSize () const
Returns the total number counted (evaluated) inputs.
virtual bool isInitialized () const
Returns true if layer has been initialized.
bool setupRequired () const
Returns true if portions of the interface must be setup.
Protected Member Functions
void save (OutputArchive &ar, VersionType version) const
Save serializer.
void load (InputArchive &ar, VersionType version)
Load serializer.
SizeType evaluateInputSize () const
Counts the number of inputs from outputs of previous layers.
OffsetType connectInputLayers ()
Connects all previous layer to Layer input.
Protected Attributes
std::map< std::string,
*
typename Self::Ptr > prev_
Pointers to previous layers.
BufferType input_buffer_
Raw input value buffer.
BufferType backward_error_buffer_
Raw backward error value buffer.
ShapeType input_shape_
Total number of input connections.
ShapeType output_shape_
Total number of output connections.
bool initialized_
Flags which indicated that layer has been initialized.
bool setup_required_
Flags which indicates that layer should be initialized normally.
Friends
template<typename LayerType >
bool connect (const typename LayerType::Ptr &from, const typename LayerType::Ptr &to)
Connects Layer objects.
Detailed Description
template<typename ValueType>class ffnn::layer::Layer< ValueType >
Base object for all layer types.
Member Typedef Documentation
template<typename ValueType> using ffnn::layer::Layer< ValueType >::Base = internal::Unique
Base type alias.
template<typename ValueType> typedef std::conditional< std::is_floating_point<ValueType>::value, std::vector<ValueType, Eigen::aligned_allocator<ValueType> >, std::vector<ValueType>, >::type ffnn::layer::Layer< ValueType >::BufferType
Buffer type standardization.
template<typename ValueType> typedef boost::shared_ptr<const Self> ffnn::layer::Layer< ValueType >::ConstPtr
Constant shared resource standardization.
template<typename ValueType> typedef ffnn::offset_type ffnn::layer::Layer< ValueType >::OffsetType
Offset type standardization.
template<typename ValueType> typedef boost::shared_ptr<Self> ffnn::layer::Layer< ValueType >::Ptr
Shared resource standardization.
template<typename ValueType> typedef ValueType ffnn::layer::Layer< ValueType >::ScalarType
Scalar type standardization.
template<typename ValueType> using ffnn::layer::Layer< ValueType >::Self = Layer<ValueType>
Self type alias.
template<typename ValueType> typedef Shape<SizeType> ffnn::layer::Layer< ValueType >::ShapeType
Dimension type standardization.
template<typename ValueType> typedef ffnn::size_type ffnn::layer::Layer< ValueType >::SizeType
Size type standardization.
Constructor & Destructor Documentation
template<typename ValueType > ffnn::layer::Layer< ValueType >::Layer (const ShapeType & input_shape, const ShapeType & output_shape)
Setup constructor.
Parameters
input_shape number of inputs to the Layer
output_shape number of outputs from the Layer
template<typename ValueType > ffnn::layer::Layer< ValueType >::~Layer () [virtual]
Member Function Documentation
template<typename ValueType> virtual bool ffnn::layer::Layer< ValueType >::backward () [pure virtual]
Backward value propagation.
Return values
true if backward-propagation succeeded
false otherwise
Implemented in ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, ffnn::layer::Hidden< ValueType, _HiddenLayerShape >, and ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >.
template<typename ValueType > Layer< ValueType >::OffsetType ffnn::layer::Layer< ValueType >::connectInputLayers () [protected]
Connects all previous layer to Layer input.
Return values
<code>input_shape_.size()</code>
template<typename ValueType> virtual OffsetType ffnn::layer::Layer< ValueType >::connectToForwardLayer (const Self & next, OffsetType offset) [pure virtual]
Maps outputs of this layer to inputs of the next.
Parameters
next a subsequent layer
offset offset index of a memory location in the input buffer of the next layer
Return values
<code>offset + output_shape_.size()
Implemented in ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, and ffnn::layer::Hidden< ValueType, _HiddenLayerShape >.
template<typename ValueType > Layer< ValueType >::SizeType ffnn::layer::Layer< ValueType >::evaluateInputSize () const [inline], [virtual]
Returns the total number counted (evaluated) inputs.
template<typename ValueType> SizeType ffnn::layer::Layer< ValueType >::evaluateInputSize () const [protected]
Counts the number of inputs from outputs of previous layers.
Returns
total input count
template<typename ValueType> virtual bool ffnn::layer::Layer< ValueType >::forward () [pure virtual]
Forward value propagation.
Return values
true if forward-propagation succeeded
false otherwise
Implemented in ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, ffnn::layer::Hidden< ValueType, _HiddenLayerShape >, and ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >.
template<typename ValueType> const BufferType& ffnn::layer::Layer< ValueType >::getBackwardErrorBuffer () const [inline]
Exposes const reference to raw data backward-error buffer.
Referenced by ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >::connectToForwardLayer().
template<typename ValueType> const BufferType& ffnn::layer::Layer< ValueType >::getInputBuffer () const [inline]
Exposes const reference to raw data input buffer.
Referenced by ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >::connectToForwardLayer().
template<typename ValueType> const ShapeType& ffnn::layer::Layer< ValueType >::getInputShape () const [inline]
Returns the Interface input dimension oject.
template<typename ValueType> const ShapeType& ffnn::layer::Layer< ValueType >::getOutputShape () const [inline]
Returns the Interface output dimension oject.
template<typename ValueType > bool ffnn::layer::Layer< ValueType >::initialize () [virtual]
Initialize the layer.
Reimplemented in ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, ffnn::layer::Hidden< ValueType, _HiddenLayerShape >, ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >, ffnn::layer::Input< ValueType, NetworkInputsAtCompileTime >, and ffnn::layer::Output< ValueType, NetworkOutputsAtCompileTime >.
template<typename ValueType> virtual bool ffnn::layer::Layer< ValueType >::isInitialized () const [inline], [virtual]
Returns true if layer has been initialized.
Return values
true if layer is initialized
false otherwise
Referenced by ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::backward(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::forward(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::update(), and ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::update().
template<typename ValueType> void ffnn::layer::Layer< ValueType >::load (InputArchive & ar, VersionType version) [protected], [virtual]
Load serializer.
Reimplemented from ffnn::internal::Unique.
Reimplemented in ffnn::layer::Hidden< ValueType, _HiddenLayerShape >.
template<typename ValueType> void ffnn::layer::Layer< ValueType >::save (OutputArchive & ar, VersionType version) const [protected], [virtual]
Save serializer.
Reimplemented from ffnn::internal::Unique.
Reimplemented in ffnn::layer::Hidden< ValueType, _HiddenLayerShape >.
template<typename ValueType> bool ffnn::layer::Layer< ValueType >::setupRequired () const [inline]
Returns true if portions of the interface must be setup.
Return values
true if reinitialization allowed
false otherwise
template<typename ValueType> virtual bool ffnn::layer::Layer< ValueType >::update () [pure virtual]
Applies layer weight updates.
Return values
true if weight update succeeded
false otherwise
Implemented in ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime, _HiddenLayerShape >, ffnn::layer::Hidden< ValueType, LayerShape, _InputBlockType, _OutputBlockType >, ffnn::layer::Hidden< ValueType, _HiddenLayerShape >, and ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >.
Friends And Related Function Documentation
template<typename ValueType> template<typename LayerType > bool connect (const typename LayerType::Ptr & from, const typename LayerType::Ptr & to) [friend]
Connects Layer objects.
Member Data Documentation
template<typename ValueType> BufferType ffnn::layer::Layer< ValueType >::backward_error_buffer_ [protected]
Raw backward error value buffer.
Referenced by ffnn::layer::Layer< ValueType >::getBackwardErrorBuffer().
template<typename ValueType> bool ffnn::layer::Layer< ValueType >::initialized_ [protected]
Flags which indicated that layer has been initialized.
Referenced by ffnn::layer::Layer< ValueType >::isInitialized().
template<typename ValueType> BufferType ffnn::layer::Layer< ValueType >::input_buffer_ [protected]
Raw input value buffer.
Referenced by ffnn::layer::Layer< ValueType >::getInputBuffer().
template<typename ValueType> ShapeType ffnn::layer::Layer< ValueType >::input_shape_ [protected]
Total number of input connections.
Referenced by ffnn::layer::Layer< ValueType >::evaluateInputSize(), ffnn::layer::Layer< ValueType >::getInputShape(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), and ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset().
template<typename ValueType> ShapeType ffnn::layer::Layer< ValueType >::output_shape_ [protected]
Total number of output connections.
Referenced by ffnn::layer::Layer< ValueType >::getOutputShape(), ffnn::optimizer::Adam< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), and ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset().
template<typename ValueType> std::map<std::string, typename Self::Ptr> ffnn::layer::Layer< ValueType >::prev_ [protected]
Pointers to previous layers.
template<typename ValueType> bool ffnn::layer::Layer< ValueType >::setup_required_ [protected]
Flags which indicates that layer should be initialized normally.
Referenced by ffnn::layer::Layer< ValueType >::setupRequired().
The documentation for this class was generated from the following files:
/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/layer/layer.h
/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/impl/layer/layer.hpp