/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/impl/layer/convolution/filter/serialization_class_definitions.hpp File Reference
Functions
template<class Archive >
void save (Archive &ar, const unsigned int version) const
Save serializer.
template<class Archive , bool T = Options::has_fixed_kernel_count>
std::enable_if< T >::type load (Archive &ar, const unsigned int version)
Load serializer.
template<class Archive , bool T = Options::has_fixed_kernel_count>
std::enable_if<!T >::type load (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int file_version)
Serializer.
Function Documentation
template<class Archive , bool T = Options::has_fixed_kernel_count> std::enable_if<T>::type load (Archive & ar, const unsigned int version)
Load serializer.
Parameters
ar input archive
version archive versioning information
Note
Statically sized version
Referenced by ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >::load(), ffnn::layer::Hidden< ValueType, Options, Extrinsics >::load(), ffnn::layer::FullyConnected< ValueType, Options, Extrinsics >::load(), ffnn::layer::Convolution< ValueType, Options, Extrinsics >::load(), and ffnn::layer::Layer< ValueType >::load().
template<class Archive , bool T = Options::has_fixed_kernel_count> std::enable_if<!T>::type load (Archive & ar, const unsigned int version)
template<class Archive > void save (Archive & ar, const unsigned int version) const
Save serializer.
Parameters
ar output archive
version archive versioning information
Referenced by ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime, _HiddenLayerShape >::save(), ffnn::layer::Hidden< ValueType, Options, Extrinsics >::save(), ffnn::layer::FullyConnected< ValueType, Options, Extrinsics >::save(), ffnn::layer::Convolution< ValueType, Options, Extrinsics >::save(), and ffnn::layer::Layer< ValueType >::save().
template<class Archive > void serialize (Archive & ar, const unsigned int file_version)
Serializer.
Parameters
ar input/output archive
version archive versioning information