/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/internal/eigen/dense_base_addons.h File Reference
Reference: http://stackoverflow.com/questions/18382457/eigen-and-boostserialize.
Functions
template<class Archive >
void save (Archive &ar, const unsigned int version) const
template<class Archive >
void load (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int file_version)
Detailed Description
Reference: http://stackoverflow.com/questions/18382457/eigen-and-boostserialize. Reference: https://gist.github.com/mtao/5798888.
Function Documentation
template<class Archive > void load (Archive & ar, const unsigned int version)
Referenced by ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime >::load(), ffnn::layer::Layer< ValueType >::load(), ffnn::layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime >::load(), ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime >::load(), and ffnn::layer::Convolution< ValueType, HeightAtCompileTime, WidthAtCompileTime, DepthAtCompileTime, FilterHeightAtCompileTime, FilterWidthAtCompileTime, FilterCountAtCompileTime, StrideAtCompileTime, EmbeddingMode >::load().
template<class Archive > void save (Archive & ar, const unsigned int version) const
Referenced by ffnn::layer::Activation< ValueType, NeuronType, SizeAtCompileTime >::save(), ffnn::layer::Layer< ValueType >::save(), ffnn::layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime >::save(), ffnn::layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime >::save(), and ffnn::layer::Convolution< ValueType, HeightAtCompileTime, WidthAtCompileTime, DepthAtCompileTime, FilterHeightAtCompileTime, FilterWidthAtCompileTime, FilterCountAtCompileTime, StrideAtCompileTime, EmbeddingMode >::save().
template<class Archive > void serialize (Archive & ar, const unsigned int file_version)