ffnn::layer Namespace Reference
Namespaces
activation
convolution
fully_connected
hidden
input
output
Classes
class Activation
Activation layer.
class Convolution
A convolution layer.
class FullyConnected
A fully-connected layer.
class Hidden
A network hidden-layer object.
class Input
A layer which handles network inputs.
class Layer
Base object for all layer types.
class Output
A layer which handles network outputs.
struct Shape
Shape structure representing the dimensions of an object with volume.
Functions
template<typename LayerType >
bool connect (const typename LayerType::Ptr &from, const typename LayerType::Ptr &to)
template<typename SizeType >
constexpr bool is_dynamic (SizeType n)
Checks if size represents a dynamic size.
template<typename SizeType >
constexpr bool is_dynamic (SizeType n, SizeType m)
Checks if a pair of sizes is dynamic.
template<typename SizeType >
constexpr bool is_dynamic (SizeType n, SizeType m, SizeType l)
Checks if a triplet of sizes is dynamic.
template<typename SizeType >
constexpr SizeType multiply_if_not_dynamic_sizes (SizeType n, SizeType m)
Multiplies a pair of sizes if all sizes are static.
template<typename SizeType >
constexpr SizeType multiply_if_not_dynamic_sizes (SizeType n, SizeType m, SizeType l)
Multiplies a triplet of sizes if all sizes are static.
template<typename SizeType >
std::ostream & operator<< (std::ostream &os, const Shape< SizeType > &dim)
Function Documentation
template<typename LayerType > bool ffnn::layer::connect (const typename LayerType::Ptr & from, const typename LayerType::Ptr & to)
template<typename SizeType > constexpr bool ffnn::layer::is_dynamic (SizeType n)
Checks if size represents a dynamic size.
Parameters
n interger dimension
Return values
true if dimension represents a dynamic size
false otherwise
Referenced by is_dynamic(), and multiply_if_not_dynamic_sizes().
template<typename SizeType > constexpr bool ffnn::layer::is_dynamic (SizeType n, SizeType m)
Checks if a pair of sizes is dynamic.
Parameters
n interger dimension
m interger dimension
Return values
true if either dimension represents a dynamic size
false otherwise
template<typename SizeType > constexpr bool ffnn::layer::is_dynamic (SizeType n, SizeType m, SizeType l)
Checks if a triplet of sizes is dynamic.
Parameters
n interger dimension
m interger dimension
l interger dimension
Return values
true if any dimension represents a dynamic size
false otherwise
template<typename SizeType > constexpr SizeType ffnn::layer::multiply_if_not_dynamic_sizes (SizeType n, SizeType m)
Multiplies a pair of sizes if all sizes are static.
Parameters
n interger dimension
m interger dimension
Return values
(n*m) if sizes are not dynamic
Eigen::Dynamic otherwise
Referenced by ffnn::layer::Shape< size_type >::size().
template<typename SizeType > constexpr SizeType ffnn::layer::multiply_if_not_dynamic_sizes (SizeType n, SizeType m, SizeType l)
Multiplies a triplet of sizes if all sizes are static.
Parameters
n interger dimension
m interger dimension
l interger dimension
Return values
(n*m*l) if sizes are not dynamic
Eigen::Dynamic otherwise
template<typename SizeType > std::ostream& ffnn::layer::operator<< (std::ostream & os, const Shape< SizeType > & dim)