ffnn::layer::internal Namespace Reference
Classes
class Interface
Base object for all layer types.
struct Shape
Functions
template<typename SizeType >
constexpr bool is_dynamic (SizeType n)
template<typename SizeType >
constexpr bool is_dynamic (SizeType n, SizeType m)
template<typename SizeType >
constexpr bool is_dynamic (SizeType n, SizeType m, SizeType l)
template<typename SizeType >
constexpr SizeType multiply_if_not_dynamic_sizes (SizeType n, SizeType m)
template<typename SizeType >
constexpr SizeType multiply_if_not_dynamic_sizes (SizeType n, SizeType m, SizeType l)
template<typename SizeType >
std::ostream & operator<< (std::ostream &os, const Shape< SizeType > &dim)
Function Documentation
template<typename SizeType > constexpr bool ffnn::layer::internal::is_dynamic (SizeType n)
Referenced by is_dynamic(), and multiply_if_not_dynamic_sizes().
template<typename SizeType > constexpr bool ffnn::layer::internal::is_dynamic (SizeType n, SizeType m)
template<typename SizeType > constexpr bool ffnn::layer::internal::is_dynamic (SizeType n, SizeType m, SizeType l)
template<typename SizeType > constexpr SizeType ffnn::layer::internal::multiply_if_not_dynamic_sizes (SizeType n, SizeType m)
Referenced by ffnn::layer::internal::Shape< SizeType >::size().
template<typename SizeType > constexpr SizeType ffnn::layer::internal::multiply_if_not_dynamic_sizes (SizeType n, SizeType m, SizeType l)
template<typename SizeType > std::ostream& ffnn::layer::internal::operator<< (std::ostream & os, const Shape< SizeType > & dim)