ffnn::layer::internal::Dimensions< SizeType > Struct Template Reference
#include `dimensions.h`
Public Member Functions
Dimensions ()
Dimensions (SizeType height, SizeType width=1, SizeType depth=1)
SizeType size () const
bool valid () const
operator SizeType () const
void operator= (SizeType count)
void operator= (const Dimensions &dim)
void save (OutputArchive &ar, VersionType version) const
Save serializer.
void load (InputArchive &ar, VersionType version)
Load serializer.
Public Attributes
SizeType height
SizeType width
SizeType depth
Constructor & Destructor Documentation
template<typename SizeType > ffnn::layer::internal::Dimensions< SizeType >::Dimensions () [inline]
template<typename SizeType > ffnn::layer::internal::Dimensions< SizeType >::Dimensions (SizeType height, SizeType width = 1, SizeType depth = 1) [inline], [explicit]
Member Function Documentation
template<typename SizeType > void ffnn::layer::internal::Dimensions< SizeType >::load (InputArchive & ar, VersionType version) [inline]
Load serializer.
Referenced by ffnn::layer::internal::Interface< CONVOLUTION_BASE_TARGS >::load().
template<typename SizeType > ffnn::layer::internal::Dimensions< SizeType >::operator SizeType () const [inline]
template<typename SizeType > void ffnn::layer::internal::Dimensions< SizeType >::operator= (SizeType count) [inline]
template<typename SizeType > void ffnn::layer::internal::Dimensions< SizeType >::operator= (const Dimensions< SizeType > & dim) [inline]
template<typename SizeType > void ffnn::layer::internal::Dimensions< SizeType >::save (OutputArchive & ar, VersionType version) const [inline]
Save serializer.
Referenced by ffnn::layer::internal::Interface< CONVOLUTION_BASE_TARGS >::save().
template<typename SizeType > SizeType ffnn::layer::internal::Dimensions< SizeType >::size () const [inline]
Referenced by ffnn::optimizer::GradientDescent< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::backward(), ffnn::layer::internal::Interface< CONVOLUTION_BASE_TARGS >::evaluateInputSize(), ffnn::optimizer::GradientDescent< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::layer::internal::Interface< CONVOLUTION_BASE_TARGS >::inputSize(), ffnn::layer::internal::Dimensions< SizeType >::operator SizeType(), ffnn::layer::internal::Interface< CONVOLUTION_BASE_TARGS >::outputSize(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset(), and ffnn::optimizer::GradientDescent< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset().
template<typename SizeType > bool ffnn::layer::internal::Dimensions< SizeType >::valid () const [inline]
Member Data Documentation
template<typename SizeType > SizeType ffnn::layer::internal::Dimensions< SizeType >::depth
Referenced by ffnn::layer::internal::Dimensions< SizeType >::load(), ffnn::layer::internal::Dimensions< SizeType >::operator=(), ffnn::layer::internal::Dimensions< SizeType >::save(), ffnn::layer::internal::Dimensions< SizeType >::size(), and ffnn::layer::internal::Dimensions< SizeType >::valid().
template<typename SizeType > SizeType ffnn::layer::internal::Dimensions< SizeType >::height
Referenced by ffnn::layer::internal::Dimensions< SizeType >::load(), ffnn::layer::internal::Dimensions< SizeType >::operator=(), ffnn::layer::internal::Dimensions< SizeType >::save(), ffnn::layer::internal::Dimensions< SizeType >::size(), and ffnn::layer::internal::Dimensions< SizeType >::valid().
template<typename SizeType > SizeType ffnn::layer::internal::Dimensions< SizeType >::width
Referenced by ffnn::layer::internal::Dimensions< SizeType >::load(), ffnn::layer::internal::Dimensions< SizeType >::operator=(), ffnn::layer::internal::Dimensions< SizeType >::save(), ffnn::layer::internal::Dimensions< SizeType >::size(), and ffnn::layer::internal::Dimensions< SizeType >::valid().
The documentation for this struct was generated from the following file:
/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/layer/internal/dimensions.h