ffnn::layer::Shape< SizeType > Struct Template Reference
Shape structure representing the dimensions of an object with volume.
#include `shape.h`
Public Member Functions
Shape ()
Shape (SizeType height, SizeType width=1, SizeType depth=1)
SizeType size () const
bool valid () const
operator SizeType () const
void operator= (SizeType count)
void operator= (const Shape &dim)
template<class Archive >
void serialize (Archive &ar, const unsigned int file_version)
Serializer.
Public Attributes
SizeType height
SizeType width
SizeType depth
Detailed Description
template<typename SizeType>struct ffnn::layer::Shape< SizeType >
Shape structure representing the dimensions of an object with volume.
Constructor & Destructor Documentation
template<typename SizeType> ffnn::layer::Shape< SizeType >::Shape () [inline]
template<typename SizeType> ffnn::layer::Shape< SizeType >::Shape (SizeType height, SizeType width = 1, SizeType depth = 1) [inline], [explicit]
Member Function Documentation
template<typename SizeType> ffnn::layer::Shape< SizeType >::operator SizeType () const [inline]
template<typename SizeType> void ffnn::layer::Shape< SizeType >::operator= (SizeType count) [inline]
template<typename SizeType> void ffnn::layer::Shape< SizeType >::operator= (const Shape< SizeType > & dim) [inline]
template<typename SizeType> template<class Archive > void ffnn::layer::Shape< SizeType >::serialize (Archive & ar, const unsigned int file_version) [inline]
Serializer.
template<typename SizeType> SizeType ffnn::layer::Shape< SizeType >::size () const [inline]
Referenced by ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::layer::Shape< SizeType >::operator SizeType(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset(), and ffnn::layer::Shape< size_type >::valid().
template<typename SizeType> bool ffnn::layer::Shape< SizeType >::valid () const [inline]
Referenced by ffnn::layer::Layer< ValueType >::Layer().
Member Data Documentation
template<typename SizeType> SizeType ffnn::layer::Shape< SizeType >::depth
Referenced by ffnn::layer::Shape< size_type >::operator=(), ffnn::layer::Shape< size_type >::serialize(), and ffnn::layer::Shape< size_type >::size().
template<typename SizeType> SizeType ffnn::layer::Shape< SizeType >::height
Referenced by ffnn::layer::Shape< size_type >::operator=(), ffnn::layer::Shape< size_type >::serialize(), and ffnn::layer::Shape< size_type >::size().
template<typename SizeType> SizeType ffnn::layer::Shape< SizeType >::width
Referenced by ffnn::layer::Shape< size_type >::operator=(), ffnn::layer::Shape< size_type >::serialize(), and ffnn::layer::Shape< size_type >::size().
The documentation for this struct was generated from the following file:
/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/layer/shape.h