ffnn::layer::internal::Shape< SizeType > Struct Template Reference
#include `shape.h`
Public Member Functions
Shape ()
Shape (SizeType height, SizeType width=1, SizeType depth=1)
SizeType size () const
bool valid () const
operator SizeType () const
void operator= (SizeType count)
void operator= (const Shape &dim)
template<class Archive >
void serialize (Archive &ar, const unsigned int file_version)
Serializer.
Public Attributes
SizeType height
SizeType width
SizeType depth
Constructor & Destructor Documentation
template<typename SizeType > ffnn::layer::internal::Shape< SizeType >::Shape () [inline]
template<typename SizeType > ffnn::layer::internal::Shape< SizeType >::Shape (SizeType height, SizeType width = 1, SizeType depth = 1) [inline], [explicit]
Member Function Documentation
template<typename SizeType > ffnn::layer::internal::Shape< SizeType >::operator SizeType () const [inline]
template<typename SizeType > void ffnn::layer::internal::Shape< SizeType >::operator= (SizeType count) [inline]
template<typename SizeType > void ffnn::layer::internal::Shape< SizeType >::operator= (const Shape< SizeType > & dim) [inline]
template<typename SizeType > template<class Archive > void ffnn::layer::internal::Shape< SizeType >::serialize (Archive & ar, const unsigned int file_version) [inline]
Serializer.
template<typename SizeType > SizeType ffnn::layer::internal::Shape< SizeType >::size () const [inline]
Referenced by ffnn::optimizer::GradientDescent< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::backward(), ffnn::layer::internal::Interface< ValueType >::evaluateInputSize(), ffnn::optimizer::GradientDescent< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::optimizer::Adam< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::initialize(), ffnn::layer::internal::Shape< SizeType >::operator SizeType(), ffnn::optimizer::GradientDescent< layer::FullyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset(), and ffnn::optimizer::GradientDescent< layer::SparselyConnected< ValueType, InputsAtCompileTime, OutputsAtCompileTime > >::reset().
template<typename SizeType > bool ffnn::layer::internal::Shape< SizeType >::valid () const [inline]
Member Data Documentation
template<typename SizeType > SizeType ffnn::layer::internal::Shape< SizeType >::depth
Referenced by ffnn::layer::internal::Shape< SizeType >::operator=(), ffnn::layer::internal::Shape< SizeType >::serialize(), ffnn::layer::internal::Shape< SizeType >::size(), and ffnn::layer::internal::Shape< SizeType >::valid().
template<typename SizeType > SizeType ffnn::layer::internal::Shape< SizeType >::height
Referenced by ffnn::layer::internal::Shape< SizeType >::operator=(), ffnn::layer::internal::Shape< SizeType >::serialize(), ffnn::layer::internal::Shape< SizeType >::size(), and ffnn::layer::internal::Shape< SizeType >::valid().
template<typename SizeType > SizeType ffnn::layer::internal::Shape< SizeType >::width
Referenced by ffnn::layer::internal::Shape< SizeType >::operator=(), ffnn::layer::internal::Shape< SizeType >::serialize(), ffnn::layer::internal::Shape< SizeType >::size(), and ffnn::layer::internal::Shape< SizeType >::valid().
The documentation for this struct was generated from the following file:
/home/briancairl/packages/src/ffnn-cpp/ffnn/include/ffnn/layer/internal/shape.h